### ISSUE TITLE
remove chakraui

### ISSUE THREAD

**Issue by osaguild** [osaguild/ipfs-uploader#22]
- less dependencies is good to npm package, I should remove chakraui and style native css.
- If remove chakraui, I can delete these packages
- @chakra-ui/react @emotion/react @emotion/styled framer-motion

**Comment by ArshErgon** [comment]
quick question is `chakra-ui` is being used inside the files too? or just remove the chakra-iu from the`package.json` dependencies?

**Comment by osaguild** [comment]
@ArshErgon 
year, chakra-ui is used on the component. but the purpose of this issue is rewrite chakra-ui component to native react component for fewer dependencies. simply deleting them is not enough.

**Comment by ArshErgon** [comment]
@osaguild okay, how will I run this locally? `yarn dev` gives an error nor `yarn run` works
```
yarn run v1.22.19
error Command "dev" not found.
```

**Comment by ArshErgon** [comment]
@osaguild okay, how will I run this locally? `yarn dev` gives an error nor `yarn run` works
```
yarn run v1.22.19
error Command "dev" not found.
```

**Comment by osaguild** [comment]
I decide using chakra-ui because chakra-ui is the default framework on my product
